--=============================================================================================================
-- RELIGION EXPANDED: RELIGION TEXT
--=============================================================================================================
INSERT OR REPLACE INTO LocalizedText
		(Language,	Tag,	Text)
VALUES
---------------------------------------------------------------------------------------------------------------
-- Pantheons
--------------------------------------------------------------------------------------------------------------- 
		('en_US',	'LOC_BELIEF_P0K_CHTHONIC_CULT_NAME',
		'Chthonic Cult'),
		('en_US',	'LOC_BELIEF_P0K_CHTHONIC_CULT_DESCRIPTION',
		'+1 [ICON_Science] Science from tiles with Breathtaking Appeal.'),
		('en_US',	'LOC_POK_BELIEF_TUNDRA_SPIRITS_NAME',
		'Tundra Spirits'),
		('en_US',	'LOC_POK_BELIEF_TUNDRA_SPIRITS_DESCRIPTION',
		'+1 [ICON_Food] Food from Tundra terrain.'),
		('en_US',	'LOC_POK_BELIEF_DESERT_MIRACLES_NAME',
		'Desert Miracles'),
		('en_US',	'LOC_POK_BELIEF_DESERT_MIRACLES_DESCRIPTION',
		'+1 [ICON_Food] Food from Desert terrain.'),
		('en_US',	'LOC_POK_BELIEF_RAINFOREST_RITUALS_NAME',
		'Rainforest Rituals'),
		('en_US',	'LOC_POK_BELIEF_RAINFOREST_RITUALS_DESCRIPTION',
		'+1 [ICON_Culture] Culture from Rainforests.'),
		('en_US',	'LOC_POK_BELIEF_HALLOWED_GROVES_NAME',
		'Hallowed Groves'),
		('en_US',	'LOC_POK_BELIEF_HALLOWED_GROVES_DESCRIPTION',
		'+1 [ICON_Faith] Faith from Woods.'),
		('en_US',	'LOC_BELIEF_P0K_PRIMORDIAL_WATERS_NAME',
		'Primordial Waters'),
		('en_US',	'LOC_BELIEF_P0K_PRIMORDIAL_WATERS_DESCRIPTION',
		'+2 [ICON_Amenities] Amenities and +2 [ICON_Housing] Housing from Holy Sites adjacent to a Coast or Lake tile.'),
		('en_US',	'LOC_POK_BELIEF_MESSENGER_GOD_NAME',
		'Messenger of the Gods'),
		('en_US',	'LOC_POK_BELIEF_MESSENGER_GOD_DESCRIPTION',
		'Receive +1 [ICON_TradeRoute] Trade Route capacity and a free Trader in the [ICON_Capital] Capital. +1 [ICON_Gold] Gold from all [ICON_TradeRoute] Trade Routes.'),
		('en_US',	'LOC_POK_BELIEF_SACRED_EMISSARIES_NAME',
		'Sacred Emissaries'),
		('en_US',	'LOC_POK_BELIEF_SACRED_EMISSARIES_DESCRIPTION',
		'Receive two City-State [ICON_Envoy] Envoys. +1 [ICON_InfluencePerTurn] Influence point per turn.'),
		('en_US',	'LOC_POK_BELIEF_GODDESS_OF_CALM_WATERS_NAME',
		'Goddess of Calm Waters'),
		('en_US',	'LOC_POK_BELIEF_GODDESS_OF_CALM_WATERS_DESCRIPTION',
		'+1 [ICON_Food] Food from Fishing Boats.'),
		('en_US',	'LOC_POK_BELIEF_ANIMAL_WORSHIP_NAME',
		'Animal Worship'),
		('en_US',	'LOC_POK_BELIEF_ANIMAL_WORSHIP_DESCRIPTION',
		'+1 [ICON_Culture] Culture from Camps.'),
		('en_US',	'LOC_POK_BELIEF_VOTIVE_OFFERINGS_NAME',
		'Votive Offerings'),
		('en_US',	'LOC_POK_BELIEF_VOTIVE_OFFERINGS_DESCRIPTION',
		'+1 [ICON_Culture] Culture from Quarries.'),
		('en_US',	'LOC_POK_BELIEF_GOD_OF_METALLURGY_NAME',
		'God of Metallurgy'),
		('en_US',	'LOC_POK_BELIEF_GOD_OF_METALLURGY_DESCRIPTION',
		'+1 [ICON_Science] Science from Mines over Luxury and Bonus resources.'),
		('en_US',	'LOC_POK_BELIEF_SUN_GOD_NAME',
		'Sun God'),
		('en_US',	'LOC_POK_BELIEF_SUN_GOD_DESCRIPTION',
		'+1 [ICON_Food] Food and +1 [ICON_Production] Production from Farms over Bonus resources.'),
---------------------------------------------------------------------------------------------------------------
-- Follower Beliefs
---------------------------------------------------------------------------------------------------------------
		('en_US',	'LOC_BELIEF_P0K_HIERATIC_SCRIPT_NAME',
		'Hieratic Script'),
		('en_US',	'LOC_BELIEF_P0K_HIERATIC_SCRIPT_DESCRIPTION',
		'Shrines and Temples provide [ICON_Science] Science equal to their intrinsic [ICON_Faith] Faith output.'),
		('en_US',	'LOC_BELIEF_P0K_WORSHIP_OF_WEALTH_NAME',
		'Worship of Wealth'),
		('en_US',	'LOC_BELIEF_P0K_WORSHIP_OF_WEALTH_DESCRIPTION',
		'+8 [ICON_Gold] Gold from World Wonders.'),
		('en_US',	'LOC_BELIEF_P0K_PROSPERITY_DOCTRINE_NAME',
		'Prosperity Doctrine'),
		('en_US',	'LOC_BELIEF_P0K_PROSPERITY_DOCTRINE_DESCRIPTION',
		'May purchase Commercial Hub and Entertainment Complex buildings with [ICON_Faith] Faith.'),
		('en_US',	'LOC_BELIEF_P0K_WORKS_RIGHTEOUSNESS_NAME',
		'Works Righteousness'),
		('en_US',	'LOC_BELIEF_P0K_WORKS_RIGHTEOUSNESS_DESCRIPTION',
		'May purchase Industrial Zone and Harbor buildings with [ICON_Faith] Faith.'),
		('en_US',	'LOC_BELIEF_P0K_BLESSED_DEDICATIONS_NAME',
		'Blessed Dedications'),
		('en_US',	'LOC_BELIEF_P0K_BLESSED_DEDICATIONS_DESCRIPTION',
		'+2 [ICON_Culture] Culture and +2 [ICON_Faith] Faith from [ICON_GreatWork_Religious] Religious art, [ICON_GreatWork_Sculpture] Sculptures, [ICON_GreatWork_Portrait] Portraits, and [ICON_GreatWork_Landscape] Landscapes.'),
		('en_US',	'LOC_BELIEF_P0K_FERVENT_SPIRIT_NAME',
		'Fervent Spirit'),
		('en_US',	'LOC_BELIEF_P0K_FERVENT_SPIRIT_DESCRIPTION',
		'+1 [ICON_Movement] Movement to Builders and Settlers trained in cities following this [ICON_Religion] Religion.'),
		('en_US',	'LOC_BELIEF_P0K_FESTIVAL_PROCESSIONS_NAME',
		'Festival Processions'),
		('en_US',	'LOC_BELIEF_P0K_FESTIVAL_PROCESSIONS_DESCRIPTION',
		'+1% [ICON_Culture] Culture for each [ICON_Citizen] Citizen following this [ICON_Religion] Religion.'),
		('en_US',	'LOC_BELIEF_P0K_HOLY_SANCTUARIES_NAME',
		'Holy Sanctuaries'),
		('en_US',	'LOC_BELIEF_P0K_HOLY_SANCTUARIES_DESCRIPTION',
		'+2 [ICON_Amenities] Amenities and +2 [ICON_Housing] Housing in cities with a World Wonder.'), 
---------------------------------------------------------------------------------------------------------------
-- Worship Beliefs
---------------------------------------------------------------------------------------------------------------
		('en_US',	'LOC_BELIEF_P0K_BASILICA_NAME',
		'Basilica'),
		('en_US',	'LOC_BELIEF_P0K_BASILICA_DESCRIPTION',
		'Allows construction of Basilicas (+3 [ICON_Faith] Faith, 1 slot for [ICON_GreatWork_Relic] Relics).'),
		('en_US',	'LOC_BELIEF_P0K_BETH_MANDA_NAME',
		'Beth Manda'),
		('en_US',	'LOC_BELIEF_P0K_BETH_MANDA_DESCRIPTION',
		'Allows construction of Beth Mandas (+3 [ICON_Faith] Faith, +2 [ICON_Gold] Gold, +1 [ICON_Production] Production).'),
		('en_US',	'LOC_BELIEF_P0K_KHALWAT_NAME',
		'Khalwat'),
		('en_US',	'LOC_BELIEF_P0K_KHALWAT_DESCRIPTION',
		'Allows construction of Khalwats (+3 [ICON_Faith] Faith, +2 [ICON_Culture] Culture).'),
		('en_US',	'LOC_BELIEF_P0K_BUTTO_NAME',
		'Buttō'),
		('en_US',	'LOC_BELIEF_P0K_BUTTO_DESCRIPTION',
		'Allows construction of Buttōs (+3 [ICON_Faith] Faith, +4 [ICON_Gold] Gold).'),
		('en_US',	'LOC_BELIEF_P0K_DERASAR_NAME',
		'Derasar'),
		('en_US',	'LOC_BELIEF_P0K_DERASAR_DESCRIPTION',
		'Allows construction of Derasars (+3 [ICON_Faith] Faith, +1 [ICON_Food] Food, +1 [ICON_Production] Production).'),
		('en_US',	'LOC_BELIEF_P0K_CANDI_NAME',
		'Candi'),
		('en_US',	'LOC_BELIEF_P0K_CANDI_DESCRIPTION',
		'Allows construction of Candis (+3 [ICON_Faith] Faith, +1 [ICON_Culture] Culture, +1 [ICON_Production] Production).'),
		('en_US',	'LOC_BELIEF_P0K_SERAPEUM_NAME',
		'Serapeum'),
		('en_US',	'LOC_BELIEF_P0K_SERAPEUM_DESCRIPTION',
		'Allows construction of Serapea (+3 [ICON_Faith] Faith, +1 [ICON_Science] Science, +1 [ICON_Production] Production).'),
---------------------------------------------------------------------------------------------------------------
-- Founder Beliefs
--------------------------------------------------------------------------------------------------------------- 
		('en_US',	'LOC_BELIEF_P0K_ECUMENICAL_COUNCIL_NAME',
		'Ecumenical Council'),
		('en_US',	'LOC_BELIEF_P0K_ECUMENICAL_COUNCIL_DESCRIPTION',
		'+1 [ICON_Science] Science for each city following this [ICON_Religion] Religion.'),
		('en_US',	'LOC_BELIEF_P0K_VERNACULAR_LITURGY_NAME',
		'Vernacular Liturgy'),
		('en_US',	'LOC_BELIEF_P0K_VERNACULAR_LITURGY_DESCRIPTION',
		'+1 [ICON_Culture] Culture for each city following this [ICON_Religion] Religion.'),
		('en_US',	'LOC_BELIEF_P0K_EVANGELISM_NAME',
		'Evangelism'),
		('en_US',	'LOC_BELIEF_P0K_EVANGELISM_DESCRIPTION',
		'+1 [ICON_Faith] Faith for every 4 followers of this [ICON_Religion] Religion.'),
---------------------------------------------------------------------------------------------------------------
-- Enhancer Beliefs
---------------------------------------------------------------------------------------------------------------
		('en_US',	'LOC_BELIEF_P0K_SACRAL_ARCHITECTURE_NAME',
		'Sacral Architecture'),
		('en_US',	'LOC_BELIEF_P0K_SACRAL_ARCHITECTURE_DESCRIPTION', 
		'+50% [ICON_Production] Production towards Holy Sites and their buildings.'),
		('en_US',	'LOC_BELIEF_P0K_WITCHCRAFT_TRIALS_NAME',
		'Witchcraft Trials'),
		('en_US',	'LOC_BELIEF_P0K_WITCHCRAFT_TRIALS_DESCRIPTION',
		'The [ICON_Faith] Faith cost of purchasing Inquisitors is reduced by 50%. Inquisitors receive +1 Remove Heresy charge.'),
		('en_US',	'LOC_BELIEF_P0K_LAYING_ON_OF_HANDS_NAME',
		'Laying on of Hands'),
		('en_US',	'LOC_BELIEF_P0K_LAYING_ON_OF_HANDS_DESCRIPTION',
		'The [ICON_Faith] Faith cost of purchasing Gurus is reduced by 50%. Gurus receive +1 Heal charge.'),
		('en_US',	'LOC_BELIEF_P0K_PIOUS_MERCHANTS_NAME',
		'Pious Merchants'),
		('en_US',	'LOC_BELIEF_P0K_PIOUS_MERCHANTS_DESCRIPTION',
		'+100% [ICON_Religion] Religious pressure from [ICON_TradeRoute] Trade Routes.'), 
		('en_US',	'LOC_BELIEF_P0K_CANONIZATION_NAME',
		'Canonization'),
		('en_US',	'LOC_BELIEF_P0K_CANONIZATION_DESCRIPTION',
		'Activating a [ICON_GreatPerson] Great Person spreads 400 [ICON_Religion] Religious pressure to cities within 10 tiles.'),
		('en_US',	'LOC_BELIEF_P0K_MILITARISTIC_SECT_NAME',
		'Militaristic Sect'),
		('en_US',	'LOC_BELIEF_P0K_MILITARISTIC_SECT_DESCRIPTION',
		'[ICON_Religion] Religious units receive +5 [ICON_Strength] Strength in theological combat.'),
		('en_US',	'LOC_BELIEF_P0K_BY_THE_SWORD_NAME',
		'By the Sword'),
		('en_US',	'LOC_BELIEF_P0K_BY_THE_SWORD_DESCRIPTION',
		'Capturing a city with a melee unit or when a melee unit is adjacent to that city automatically converts it to your majority [ICON_Religion] Religion.');