CREATE TABLE IF NOT EXISTS SC_Rihla_Writers
(	WriterType 							text,
	EraType		  						number,
	WriterTextType						text);

CREATE TABLE IF NOT EXISTS SC_Rihla_Lists
(	ListType 							text,
	RankingType							text);

-- MALE: "has completed his greatest work, the list of"
-- FEMALE: "has completed her greatest work, the list of"
-- NEUTRAL_OUTSIDE: "has provided us with information allowing us to compile a list of"
-- NEUTRAL: "has completed their greatest work, the list of"
-- HAS_FOUND: "has found that these are the"
-- PLURAL: "have completed their greatest work yet, the list of"

INSERT INTO SC_Rihla_Writers
		(WriterType,						EraType,	WriterTextType)
VALUES	('SC_RIHLA_ANCIENT_1',				0,			'PLURAL'),
		('SC_RIHLA_ANCIENT_2',				0,			'NEUTRAL_OUTSIDE'),
		('SC_RIHLA_ANCIENT_3',				0,			'ORACLE'),
		('SC_RIHLA_ANCIENT_4',				0,			'NEUTRAL_OUTSIDE'),
		('SC_RIHLA_ANCIENT_5',				0,			'NEUTRAL_OUTSIDE'),
		('SC_RIHLA_ANCIENT_6',				0,			'NEUTRAL_OUTSIDE'),
		('SC_RIHLA_ANCIENT_7',				0,			'RUMORS'),
		('SC_RIHLA_ANCIENT_8',				0,			'PLURAL'),
		('SC_RIHLA_ANCIENT_9',				0,			'NEUTRAL_OUTSIDE'),
		('SC_RIHLA_ANCIENT_10',				0,			'LEGENDS'),

		('SC_RIHLA_CLASSICAL_1',			1,			'MALE'),
		('SC_RIHLA_CLASSICAL_2',			1,			'MALE'),
		('SC_RIHLA_CLASSICAL_3',			1,			'FEMALE'),
		('SC_RIHLA_CLASSICAL_4',			1,			'MALE'),
		('SC_RIHLA_CLASSICAL_5',			1,			'MALE'),
		('SC_RIHLA_CLASSICAL_6',			1,			'MALE'),
		('SC_RIHLA_CLASSICAL_7',			1,			'MALE'),
		('SC_RIHLA_CLASSICAL_8',			1,			'MALE'),
		('SC_RIHLA_CLASSICAL_9',			1,			'MALE'),
		('SC_RIHLA_CLASSICAL_10',			1,			'MALE'),

		('SC_RIHLA_MEDIEVAL_1',				2,			'MALE'),
		('SC_RIHLA_MEDIEVAL_2',				2,			'MALE'),
		('SC_RIHLA_MEDIEVAL_3',				2,			'MALE'),
		('SC_RIHLA_MEDIEVAL_4',				2,			'MALE'),
		('SC_RIHLA_MEDIEVAL_5',				2,			'MALE'),
		('SC_RIHLA_MEDIEVAL_6',				2,			'FEMALE'),
		('SC_RIHLA_MEDIEVAL_7',				2,			'MALE'),
		('SC_RIHLA_MEDIEVAL_8',				2,			'MALE'),
		('SC_RIHLA_MEDIEVAL_9',				2,			'MALE'),
		('SC_RIHLA_MEDIEVAL_10',			2,			'MALE'),

		('SC_RIHLA_RENAISSANCE_1',			3,			'FEMALE'),
		('SC_RIHLA_RENAISSANCE_2',			3,			'MALE'),
		('SC_RIHLA_RENAISSANCE_3',			3,			'MALE'),
		('SC_RIHLA_RENAISSANCE_4',			3,			'MALE'),
		('SC_RIHLA_RENAISSANCE_5',			3,			'MALE'),
		('SC_RIHLA_RENAISSANCE_6',			3,			'MALE'),
		('SC_RIHLA_RENAISSANCE_7',			3,			'MALE'),
		('SC_RIHLA_RENAISSANCE_8',			3,			'MALE'),
		('SC_RIHLA_RENAISSANCE_9',			3,			'MALE'),
		('SC_RIHLA_RENAISSANCE_10',			3,			'MALE'),

		('SC_RIHLA_INDUSTRIAL_1',			4,			'MALE'),
		('SC_RIHLA_INDUSTRIAL_2',			4,			'FEMALE'),
		('SC_RIHLA_INDUSTRIAL_3',			4,			'FEMALE'),
		('SC_RIHLA_INDUSTRIAL_4',			4,			'MALE'),
		('SC_RIHLA_INDUSTRIAL_5',			4,			'FEMALE'),
		('SC_RIHLA_INDUSTRIAL_6',			4,			'MALE'),
		('SC_RIHLA_INDUSTRIAL_7',			4,			'MALE'),
		('SC_RIHLA_INDUSTRIAL_8',			4,			'FEMALE'),
		('SC_RIHLA_INDUSTRIAL_9',			4,			'MALE'),
		('SC_RIHLA_INDUSTRIAL_10',			4,			'MALE'),

		('SC_RIHLA_MODERN_1',				5,			'FEMALE'),
		('SC_RIHLA_MODERN_2',				5,			'FEMALE'),
		('SC_RIHLA_MODERN_3',				5,			'MALE'),
		('SC_RIHLA_MODERN_4',				5,			'FEMALE'),
		('SC_RIHLA_MODERN_5',				5,			'FEMALE'),
		('SC_RIHLA_MODERN_6',				5,			'MALE'),
		('SC_RIHLA_MODERN_7',				5,			'MALE'),
		('SC_RIHLA_MODERN_8',				5,			'FEMALE'),
		('SC_RIHLA_MODERN_9',				5,			'MALE'),
		('SC_RIHLA_MODERN_10',				5,			'FEMALE'),

		('SC_RIHLA_ATOMIC_1',				6,			'FEMALE'),
		('SC_RIHLA_ATOMIC_2',				6,			'MALE'),
		('SC_RIHLA_ATOMIC_3',				6,			'MALE'),
		('SC_RIHLA_ATOMIC_4',				6,			'MALE'),
		('SC_RIHLA_ATOMIC_5',				6,			'FEMALE'),
		('SC_RIHLA_ATOMIC_6',				6,			'MALE'),
		('SC_RIHLA_ATOMIC_7',				6,			'MALE'),
		('SC_RIHLA_ATOMIC_8',				6,			'MALE'),
		('SC_RIHLA_ATOMIC_9',				6,			'MALE'),
		('SC_RIHLA_ATOMIC_10',				6,			'FEMALE'),

		('SC_RIHLA_INFORMATION_1',			7,			'MALE'),
		('SC_RIHLA_INFORMATION_2',			7,			'FEMALE'),
		('SC_RIHLA_INFORMATION_3',			7,			'MALE'),
		('SC_RIHLA_INFORMATION_4',			7,			'MALE'),
		('SC_RIHLA_INFORMATION_5',			7,			'MALE'),
		('SC_RIHLA_INFORMATION_6',			7,			'MALE'),
		('SC_RIHLA_INFORMATION_7',			7,			'MALE'),
		('SC_RIHLA_INFORMATION_8',			7,			'MALE'),
		('SC_RIHLA_INFORMATION_9',			7,			'MALE'),
		('SC_RIHLA_INFORMATION_10',			7,			'NEUTRAL'),

		('SC_RIHLA_FUTURE_1',				8,			'AI'),
		('SC_RIHLA_FUTURE_2',				8,			'HAS_FOUND'),
		('SC_RIHLA_FUTURE_3',				8,			'HAS_FOUND'),
		('SC_RIHLA_FUTURE_4',				8,			'NEUTRAL'),
		('SC_RIHLA_FUTURE_5',				8,			'NEUTRAL'),
		('SC_RIHLA_FUTURE_6',				8,			'MEME'),
		('SC_RIHLA_FUTURE_7',				8,			'PLURAL'),
		('SC_RIHLA_FUTURE_8',				8,			'HAS_FOUND'),
		('SC_RIHLA_FUTURE_9',				8,			'SATELLITES'),
		('SC_RIHLA_FUTURE_10',				8,			'HAS_FOUND');

INSERT INTO SC_Rihla_Lists
		(ListType,							RankingType)
VALUES	('SC_RIHLA_LIST_FOOD',				'Civ'),
		('SC_RIHLA_LIST_PRODUCTION',		'Civ'),
		('SC_RIHLA_LIST_GOLD',				'Civ'),
		('SC_RIHLA_LIST_TECH',				'Civ'),
		('SC_RIHLA_LIST_CIVICS',			'Civ'),
		('SC_RIHLA_LIST_AMENITIES',			'Civ'),
		('SC_RIHLA_LIST_WONDERS',			'Civ'),
		('SC_RIHLA_LIST_MILITARY',			'Civ'),
		('SC_RIHLA_LIST_FAITH_TURN',		'Civ'),
		('SC_RIHLA_LIST_POPULATION',		'Civ'),
		('SC_RIHLA_LIST_GOLD_TURN',			'Civ'),
		('SC_RIHLA_LIST_SCIENCE_TURN',		'Civ'),
		('SC_RIHLA_LIST_CULTURE_TURN',		'Civ'),
		('SC_RIHLA_LIST_GREAT_PEOPLE',		'Civ'),
		('SC_RIHLA_LIST_TRADE_ROUTES',		'Civ'),
		('SC_RIHLA_LIST_GREAT_WORKS',		'Civ'),
		('SC_RIHLA_LIST_WIDE',				'Civ'),
		('SC_RIHLA_LIST_TALL',				'Civ'),
		('SC_RIHLA_LIST_TOURISM',			'Civ'),
		('SC_RIHLA_LIST_FAITH',				'Civ'),
		('SC_RIHLA_LIST_DEVELOPED',			'Civ'),
		('SC_RIHLA_LIST_GREEN',				'Civ'),
		('SC_RIHLA_LIST_NAVAL',				'Civ'),
		('SC_RIHLA_LIST_CAPTURES',			'Civ'),
		('SC_RIHLA_LIST_SUZERAINS',			'Civ'),
		('SC_RIHLA_LIST_PARKS',				'Civ'),
		('SC_RIHLA_LIST_LUXURIES',			'Civ'),
		('SC_RIHLA_LIST_SCORE',				'Civ'),
		('SC_RIHLA_LIST_POLLUTION',			'Civ'),
		('SC_RIHLA_LIST_GOVERNORS',			'Civ'),
		('SC_RIHLA_LIST_IMPROVED',			'Civ'),
		('SC_RIHLA_LIST_LOYAL',				'Civ'),

		('SC_RIHLA_LIST_TOURISM_CITY',		'City'),
		('SC_RIHLA_LIST_PRODUCTION_CITY',	'City'),
		('SC_RIHLA_LIST_GOLD_CITY',			'City'),
		('SC_RIHLA_LIST_CULTURE_CITY',		'City'),
		('SC_RIHLA_LIST_FOOD_CITY',			'City'),
		('SC_RIHLA_LIST_SCIENCE_CITY',		'City'),
		('SC_RIHLA_LIST_POPULATION_CITY',	'City'),
		('SC_RIHLA_LIST_POWER_CITY',		'City'),
		('SC_RIHLA_LIST_HOUSING_CITY',		'City'),
		('SC_RIHLA_LIST_FAITH_CITY',		'City'),
		('SC_RIHLA_LIST_AMENITIES_CITY',	'City');