-- UC_CMP_Text_CivEx
-- Author: JNR
--------------------------------------------------------------

-- English
--------------------------------------------------------------
INSERT OR REPLACE INTO EnglishText
		(Tag,																		Text)
VALUES	('LOC_DISTRICT_OBSERVATORY_DESCRIPTION_JNR_UC_CX',							'A district unique to the Maya for scientific endeavors. Replaces the Campus. Buildings in this district may be purchased with [ICON_Faith] Faith. +1 [ICON_GreatProphet] Great Prophet point.[NEWLINE][NEWLINE]+1 [ICON_Science] Science bonus for each adjacent Luxury Resource and Plantation. +1 [ICON_Science] Science bonus for every two adjacent Farms or districts.[NEWLINE][NEWLINE]Unlocks the Venus Observations unique project, which provides [ICON_Faith] Faith and increased [ICON_Religion] Religious pressure while active, and [ICON_GreatProphet] Great Prophet points and a random [ICON_TechBoosted] Eureka upon completion.'),
		('LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_EXPANSION2_DESCRIPTION_JNR_UC_CX',	'Dedications for [ICON_Glory_Golden_Age] Golden Ages also grant the normal [ICON_Glory_Normal_Age] Era Score bonus. +1 [ICON_Amenities] Amenity and +1 [ICON_Housing] Housing in all cities during [ICON_Glory_Golden_Age] Golden Ages. Receive a random Civic after unlocking the Political Philosophy civic. [ICON_TechBoosted] Eurekas and [ICON_CivicBoosted] Inspirations grant an additional +10% boost. City Centers gain bonus yields based on which district building is constructed first: +2 [ICON_Science] Science from Level 1 Campus buildings, +2 [ICON_Culture] Culture from Level 1 Theater Square buildings, and +2 [ICON_Faith] Faith from Level 1 Holy Site buildings.'),
		('LOC_TRAIT_CIVILIZATION_PAX_BRITANNICA_EXPANSION2_DESCRIPTION_JNR_UC_CX',	'Cities on England''s home continent receive [ICON_Science] Science from Campus buildings equal to the building level and +1 [ICON_Amenities] Amenity. Cities on foreign continents receive [ICON_Production] Production from Industrial Zone buildings equal to the building level and +1 [ICON_Housing] Housing. Completing an Industrial Zone triggers a Culture Bomb. +1 [ICON_TradeRoute] Trade Route capacity for each type of Strategic resource improved in English territory. Gain access to the Redcoat unique unit after unlocking the Military Science technology.'),
		('LOC_TRAIT_CIVILIZATION_IMPERIAL_FREE_CITIES_DESCRIPTION_JNR_UC_CX',		'Each city may construct one more district than usual (exceeding the normal limit based on [ICON_Citizen] Population). [ICON_TradeRoute] Trade Routes to German cities gain +1 [ICON_Food] Food, +1 [ICON_Production] Production, and +1 [ICON_Gold] Gold per specialty district in the destination city. Level 2 buildings in Campuses, Industrial Zones, and Commercial Hubs provide +2 of their respective yields. Additionally, these buildings each grant +1 [ICON_Citizen] Population and +1 [ICON_Housing] Housing.'),
		('LOC_TRAIT_LEADER_TRAJANS_COLUMN_DESCRIPTION_JNR_UC_CX',					'Each city begins with a free Monument. City borders expand 15% faster. Farms receive +1 of the appropriate yield when adjacent to a Level 1 Building from the Campus, Theater Square, Holy Site, Industrial Zone, Commercial Hub, or Habor. Receive a Settler in the [ICON_Capital] Capital upon unlocking the Political Philosophy civic.'),
		('LOC_TRAIT_LEADER_HWARANG_DESCRIPTION_JNR_UC_CX',							'Recruiting a [ICON_GreatProphet] Great Prophet or a [ICON_GreatScientist] Great Scientist grants +1 [ICON_Governor] Governor Title and +1 [ICON_TradeRoute] Trade Route capacity. [ICON_Governor] Governors provide +3% [ICON_Science] Science and +3% [ICON_Culture] Culture to their cities for each Promotion. Campus buildings provide [ICON_Faith] Faith equal to their level +1.'),
		('LOC_TRAIT_CIVILIZATION_NOBEL_PRIZE_DESCRIPTION_JNR_UC_CX',				'+25% [ICON_GreatPerson] Great Person points in cities that have a Campus with a high [ICON_Science] Science adjacency bonus. Receive a random [ICON_TechBoosted] Eureka upon constructing a University or Academy. Earning a [ICON_GreatPerson] Great Person grants 50 [ICON_Favor] Diplomatic Favor. +20% [ICON_Production] Production towards district projects.');
--------------------------------------------------------------

-- Portuguese
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText
		(Language,	Tag,																		Text)
VALUES	('pt_BR',	'LOC_DISTRICT_OBSERVATORY_DESCRIPTION_JNR_UC_CX',							'Um distrito único da civilizaçăo Maia para assuntos científicos. Subsitui o Campus. Edificaçőes neste distrito podem ser comprados com [ICON_Faith] Fé. +1 ponto de [ICON_GreatProphet] Grande Profeta por turno.[NEWLINE][NEWLINE]+1 de [ICON_SCIENCE] Cięncia bonus for each adjacent Luxury Resource and Plantation. +1 de [ICON_SCIENCE] Cięncia para cada 2 painéis de melhorias de fazenda ou painéis de distrito.[NEWLINE][NEWLINE]Habilita o projeto único Observaçőes de Vęnus, que fornece [ICON_Faith] Fé e uma maior [ICON_Religion] pressăo religiosa enquanto ativa, e pontos de [ICON_GreatProphet] Grande Profeta e uma [ICON_TechBoosted] Eureka ao seu término.'),
		('pt_BR',	'LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_EXPANSION2_DESCRIPTION_JNR_UC_CX',	'Dedicaçőes para [ICON_Glory_Golden_Age] Eras Douradas também dăo o bônus de [ICON_Glory_Normal_Age] Pontos de Era Score. +1 de [ICON_Amenities] Serviços e +1 de [ICON_Housing] Habitaçăo em todas as cidades durante [ICON_Glory_Golden_Age] Eras Douradas. Receba um Cívico aleatório depois de descobrir o cívico Filosofia Política. [ICON_TechBoosted] Eurekas e [ICON_CivicBoosted] Inspiraçőes dăo um bônus adicional de +10%. Centros de Cidade ganham bônus baseados em qual edificaçăo é construída primeiro: +2 de [ICON_SCIENCE] Cięncia de edificaçőes de Campus nível 1, +2 de [ICON_Culture] Cultura de edificaçőes de Teatro nível 1, and +2 de [ICON_Faith] Fé de edificaçőes de Local Sagrado nível 1.'),
		('pt_BR',	'LOC_TRAIT_CIVILIZATION_PAX_BRITANNICA_EXPANSION2_DESCRIPTION_JNR_UC_CX',	'Cities on England''s home continent receive de [ICON_SCIENCE] Cięncia from Campus buildings equal to the building level and +1 [ICON_Amenities] Amenity. Cities on foreign continents receive [ICON_Production] Production from Industrial Zone buildings equal to the building level and +1 [ICON_Housing] Housing. Completing an Industrial Zone triggers a Culture Bomb. +1 [ICON_TradeRoute] Trade Route capacity for each type of Strategic resource improved in English territory. Gain access to the Redcoat unique unit after unlocking the Military Science technology.'),
		('pt_BR',	'LOC_TRAIT_CIVILIZATION_IMPERIAL_FREE_CITIES_DESCRIPTION_JNR_UC_CX',		'Cada cidade pode construir um distrito a mais que o normal (excedendo o limite normal baseado na [ICON_Citizen] Populaçăo). [ICON_TradeRoute] Rotas Comerciais para cidades Alemăs ganham +1 de [ICON_Food] Alimento, +1 de [ICON_Production] Produçăo e +1 de [ICON_Gold] Ouro por distrito especializado na cidade de destino. Edificaçőes de nível 2 em Campi, Zonas Industriais e Centros Comerciais fornecem +2 dos seus bônus respectivos. Adicionalmente, estas edificaçőes concedem +1 de [ICON_Citizen] Populaçăo e +1 de [ICON_Housing] Habitaçăo.'),
		('pt_BR',	'LOC_TRAIT_LEADER_TRAJANS_COLUMN_DESCRIPTION_JNR_UC_CX',					'Cada cidade começa com um monumento gratuito. As fronteiras das cidades se expandem 15% mais rápido. Fazendo recebem +1 do bônus apropriado quando adjacente a um Campus, Teatro, Lugar Sagrado, Zona Industrial, Centro Comercial ou Porto com uma edificaçăo nível 1. Receba um Colonizador na [ICON_Capital] Capital ao descobrir o Cívico Filosofia Política.'),
		('pt_BR',	'LOC_TRAIT_LEADER_HWARANG_DESCRIPTION_JNR_UC_CX',							'Recrutar um [ICON_GreatProphet] Grande Profeta ou um [ICON_GreatScientist] Grande Cientista concede +1 título de [ICON_Governor] Governador e +1 capacidade de [ICON_TradeRoute] Rota Comercial. [ICON_Governor] Governadores dăo +3% de [ICON_SCIENCE] Cięncia e +3% de [ICON_Culture] Cultura para a cidade em que estăo estabelecidos para cada Promoçăo que possuírem. Edificaçőes em Campus fornecem [ICON_Faith] Fé igual ao seu nível +1.'),
		('pt_BR',	'LOC_TRAIT_CIVILIZATION_NOBEL_PRIZE_DESCRIPTION_JNR_UC_CX',					'+25% de pontos de [ICON_GreatPerson] Grandes Personalidades em cidades que tenham um Campus com um alto bônus de adjacęncia de [ICON_SCIENCE] Cięncia. Receba uma [ICON_TechBoosted] Eureka aleatória ao construir uma Universidade ou Academia. Recrutar uma [ICON_GreatPerson] Grande Personalidade dá 50 de [ICON_Favor] Favor Diplomático. +20% de [ICON_Production] Produçăo para projetos de distritos.');
--------------------------------------------------------------