-- UC_MIL_Icons
-- Author: JNR
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR IGNORE INTO IconDefinitions
		(Name,									Atlas,						'Index')
VALUES	('ICON_BUILDING_JNR_TARGET_RANGE',		'ICON_ATLAS_BUILDINGS',		13),
		('ICON_BUILDING_JNR_CAVALIER',			'ICON_ATLAS_BUILDINGS',		21),
		('ICON_BUILDING_JNR_DEPOT',				'ICON_ATLAS_BUILDINGS',		21),
		('ICON_BUILDING_JNR_ARSENAL',			'ICON_ATLAS_BUILDINGS',		29),
		('ICON_BUILDING_JNR_PRISON',			'ICON_ATLAS_BUILDINGS',		29),
		('ICON_BUILDING_JNR_NAVAL_BASE',		'ICON_ATLAS_BUILDINGS',		33),

		('ICON_BUILDING_JNR_TARGET_RANGE_FOW',	'ICON_ATLAS_BUILDINGS_FOW',	13),
		('ICON_BUILDING_JNR_CAVALIER_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	21),
		('ICON_BUILDING_JNR_DEPOT_FOW',			'ICON_ATLAS_BUILDINGS_FOW',	21),
		('ICON_BUILDING_JNR_ARSENAL_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	29),
		('ICON_BUILDING_JNR_PRISON_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	29),
		('ICON_BUILDING_JNR_NAVAL_BASE_FOW',	'ICON_ATLAS_BUILDINGS_FOW',	33);
--------------------------------------------------------------