-- UC_REL_Worship_Icons
-- Author: JNR
--------------------------------------------------------------

-- IconTextureAtlases
--------------------------------------------------------------
INSERT INTO IconTextureAtlases
		(Name,											IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',		32,			3,				3,				'UC_REL_Worship_Buildings32.dds'),
		('ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',		38,			3,				3,				'UC_REL_Worship_Buildings38.dds'),
		('ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',		50,			3,				3,				'UC_REL_Worship_Buildings50.dds'),
		('ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',		80,			3,				3,				'UC_REL_Worship_Buildings80.dds'),
		('ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',		128,		3,				3,				'UC_REL_Worship_Buildings128.dds'),
		('ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',		256,		3,				3,				'UC_REL_Worship_Buildings256.dds');
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,									Atlas,										'Index')
VALUES	('ICON_BUILDING_JNR_CANDI',				'ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',	0),
		('ICON_BUILDING_JNR_DAOGUAN',			'ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',	1),
		('ICON_BUILDING_JNR_JINJA',				'ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',	2),
		('ICON_BUILDING_JNR_KHALWAT',			'ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',	3),
		('ICON_BUILDING_JNR_MANDIR',			'ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',	4),
		('ICON_BUILDING_JNR_MBARI',				'ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',	5),
		('ICON_BUILDING_JNR_PERIPTEROS',		'ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',	6),
		('ICON_BUILDING_JNR_SOBOR',				'ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',	7),
		('ICON_BUILDING_JNR_TZACUALLI',			'ICON_ATLAS_JNR_UC_REL_WORSHIP_BUILDINGS',	8),

		('ICON_BUILDING_JNR_CANDI_FOW',			'ICON_ATLAS_BUILDINGS_FOW',					43),
		('ICON_BUILDING_JNR_DAOGUAN_FOW',		'ICON_ATLAS_BUILDINGS_FOW',					41),
		('ICON_BUILDING_JNR_JINJA_FOW',			'ICON_ATLAS_BUILDINGS_FOW',					44),
		('ICON_BUILDING_JNR_KHALWAT_FOW',		'ICON_ATLAS_BUILDINGS_FOW',					48),
		('ICON_BUILDING_JNR_MANDIR_FOW',		'ICON_ATLAS_BUILDINGS_FOW',					47),
		('ICON_BUILDING_JNR_MBARI_FOW',			'ICON_ATLAS_BUILDINGS_FOW',					42),
		('ICON_BUILDING_JNR_PERIPTEROS_FOW',	'ICON_ATLAS_BUILDINGS_FOW',					40),
		('ICON_BUILDING_JNR_SOBOR_FOW',			'ICON_ATLAS_BUILDINGS_FOW',					45),
		('ICON_BUILDING_JNR_TZACUALLI_FOW',		'ICON_ATLAS_BUILDINGS_FOW',					46),

		('ICON_BELIEF_JNR_CANDI',				'ICON_ATLAS_BELIEFS_PATHEON',				22),
		('ICON_BELIEF_JNR_DAOGUAN',				'ICON_ATLAS_BELIEFS_PATHEON',				22),
		('ICON_BELIEF_JNR_JINJA',				'ICON_ATLAS_BELIEFS_PATHEON',				22),
		('ICON_BELIEF_JNR_KHALWAT',				'ICON_ATLAS_BELIEFS_PATHEON',				22),
		('ICON_BELIEF_JNR_MANDIR',				'ICON_ATLAS_BELIEFS_PATHEON',				22),
		('ICON_BELIEF_JNR_MBARI',				'ICON_ATLAS_BELIEFS_PATHEON',				22),
		('ICON_BELIEF_JNR_PERIPTEROS',			'ICON_ATLAS_BELIEFS_PATHEON',				22),
		('ICON_BELIEF_JNR_SOBOR',				'ICON_ATLAS_BELIEFS_PATHEON',				22),
		('ICON_BELIEF_JNR_TZACUALLI',			'ICON_ATLAS_BELIEFS_PATHEON',				22);
--------------------------------------------------------------