-- UC_PRD_Icons
-- Author: JNR
--------------------------------------------------------------

-- IconTextureAtlases
--------------------------------------------------------------	
INSERT INTO IconTextureAtlases	
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_JNR_UC_PRD_RESOURCES',		256,	 	4,				4,				'UC_PRD_Resources256.dds'),
		('ICON_ATLAS_JNR_UC_PRD_RESOURCES',		64,	 		4,				4,				'UC_PRD_Resources64.dds'),
		('ICON_ATLAS_JNR_UC_PRD_RESOURCES',		50,	 		4,				4,				'UC_PRD_Resources50.dds'),
		('ICON_ATLAS_JNR_UC_PRD_RESOURCES',		38,	 		4,				4,				'UC_PRD_Resources38.dds'),
		('ICON_ATLAS_JNR_UC_PRD_RESOURCES_FOW',	256,	 	4,				4,				'UC_PRD_Resources256_FOW.dds');

INSERT INTO IconTextureAtlases	
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Filename,					Baseline)
VALUES  ('ICON_ATLAS_JNR_UC_PRD_RESOURCES',		22,	 		4,				4,				'UC_PRD_Resources22.dds',	6);

INSERT INTO IconTextureAtlases
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		256,		4,				4,				'UC_PRD_Products256.dds'),
		('ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		64,			4,				4,				'UC_PRD_Products64.dds'),
		('ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		50,			4,				4,				'UC_PRD_Products50.dds'),
		('ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		38,			4,				4,				'UC_PRD_Products38.dds'),
		('ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		32,			4,				4,				'UC_PRD_Products32.dds'),
		('ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	256,		4,				4,				'UC_PRD_Products256_FOW.dds');
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------	
INSERT INTO IconDefinitions	
		(Name,														Atlas, 									'Index')
VALUES	('RESOURCE_JNR_MACHINES',									'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		0),
		('ICON_RESOURCE_JNR_MACHINES',								'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		0),
		('ICON_RESOURCE_JNR_MACHINES_FOW',							'ICON_ATLAS_JNR_UC_PRD_RESOURCES_FOW',	0),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_MACHINES',			'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		0),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_MACHINES_',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		0),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_MACHINES__FOW',	'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	0),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_MACHINES_FOW',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	0),
		('ICON_PROJECT_CREATE_PRODUCT_JNR_MACHINES',				'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		0),

		('RESOURCE_JNR_FERTILIZERS',								'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		1),
		('ICON_RESOURCE_JNR_FERTILIZERS',							'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		1),
		('ICON_RESOURCE_JNR_FERTILIZERS_FOW',						'ICON_ATLAS_JNR_UC_PRD_RESOURCES_FOW',	1),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_FERTILIZERS',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		1),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_FERTILIZERS_',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		1),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_FERTILIZERS_FOW',	'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	1),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_FERTILIZERS__FOW',	'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	1),
		('ICON_PROJECT_CREATE_PRODUCT_JNR_FERTILIZERS',				'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		1),

		('RESOURCE_JNR_ELECTRONICS',								'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		2),
		('ICON_RESOURCE_JNR_ELECTRONICS',							'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		2),
		('ICON_RESOURCE_JNR_ELECTRONICS_FOW',						'ICON_ATLAS_JNR_UC_PRD_RESOURCES_FOW',	2),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_ELECTRONICS',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		2),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_ELECTRONICS_',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		2),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_ELECTRONICS_FOW',	'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	2),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_ELECTRONICS__FOW',	'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	2),
		('ICON_PROJECT_CREATE_PRODUCT_JNR_ELECTRONICS',				'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		2),

		('RESOURCE_JNR_SOUVENIRS',									'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		3),
		('ICON_RESOURCE_JNR_SOUVENIRS',								'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		3),
		('ICON_RESOURCE_JNR_SOUVENIRS_FOW',							'ICON_ATLAS_JNR_UC_PRD_RESOURCES_FOW',	3),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_SOUVENIRS',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		3),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_SOUVENIRS_',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		3),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_SOUVENIRS_FOW',	'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	3),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_SOUVENIRS__FOW',	'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	3),
		('ICON_PROJECT_CREATE_PRODUCT_JNR_SOUVENIRS',				'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		3),

		('RESOURCE_JNR_PHARMA',										'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		4),
		('ICON_RESOURCE_JNR_PHARMA',								'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		4),
		('ICON_RESOURCE_JNR_PHARMA_FOW',							'ICON_ATLAS_JNR_UC_PRD_RESOURCES_FOW',	4),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_PHARMA',			'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		4),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_PHARMA_',			'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		4),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_PHARMA_FOW',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	4),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_PHARMA__FOW',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	4),
		('ICON_PROJECT_CREATE_PRODUCT_JNR_PHARMA',					'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		4),

		('RESOURCE_JNR_PLASTICS',									'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		5),
		('ICON_RESOURCE_JNR_PLASTICS',								'ICON_ATLAS_JNR_UC_PRD_RESOURCES',		5),
		('ICON_RESOURCE_JNR_PLASTICS_FOW',							'ICON_ATLAS_JNR_UC_PRD_RESOURCES_FOW',	5),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_PLASTICS',			'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		5),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_PLASTICS_',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		5),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_PLASTICS_FOW',		'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	5),
		('ICON_MONOPOLIES_AND_CORPS_RESOURCE_JNR_PLASTICS__FOW',	'ICON_ATLAS_JNR_UC_PRD_PRODUCTS_FOW',	5),
		('ICON_PROJECT_CREATE_PRODUCT_JNR_PLASTICS',				'ICON_ATLAS_JNR_UC_PRD_PRODUCTS',		5);
--------------------------------------------------------------