-- UC_COM_Icons
-- Author: JNR
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR IGNORE INTO IconDefinitions
		(Name,											Atlas,						'Index')
VALUES	('ICON_BUILDING_JNR_MINT',						'ICON_ATLAS_BUILDINGS',		11),
		('ICON_BUILDING_JNR_WAYSTATION',				'ICON_ATLAS_BUILDINGS',		11),
		('ICON_BUILDING_JNR_GUILDHALL',					'ICON_ATLAS_BUILDINGS',		23),
		('ICON_BUILDING_JNR_MERCHANT_QUARTER',			'ICON_ATLAS_BUILDINGS',		23),
		('ICON_BUILDING_JNR_COMMODITY_EXCHANGE',		'ICON_ATLAS_BUILDINGS',		28),
		('ICON_BUILDING_JNR_MARKETING_AGENCY',			'ICON_ATLAS_BUILDINGS',		28),
		('ICON_BUILDING_JNR_WHARF_BASE',				'ICON_ATLAS_BUILDINGS',		22),
		('ICON_BUILDING_JNR_WHARF_FISHING',				'ICON_ATLAS_BUILDINGS',		22),
		('ICON_BUILDING_JNR_WHARF_TRADE',				'ICON_ATLAS_BUILDINGS',		22),
		('ICON_BUILDING_JNR_LIGHTHOUSE_TRADE',			'ICON_ATLAS_BUILDINGS',		10),
		('ICON_BUILDING_JNR_HAVEN',						'ICON_ATLAS_BUILDINGS',		22),
		('ICON_BUILDING_JNR_CONSULATE',					'ICON_ATLAS_BUILDINGS',		22),
		('ICON_BUILDING_JNR_CRUISE_TERMINAL',			'ICON_ATLAS_BUILDINGS',		33),

		('ICON_BUILDING_JNR_MINT_FOW',					'ICON_ATLAS_BUILDINGS_FOW',	11),
		('ICON_BUILDING_JNR_WAYSTATION_FOW',			'ICON_ATLAS_BUILDINGS_FOW',	11),
		('ICON_BUILDING_JNR_GUILDHALL_FOW',				'ICON_ATLAS_BUILDINGS_FOW',	23),
		('ICON_BUILDING_JNR_MERCHANT_QUARTER_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	23),
		('ICON_BUILDING_JNR_COMMODITY_EXCHANGE_FOW',	'ICON_ATLAS_BUILDINGS_FOW',	28),
		('ICON_BUILDING_JNR_MARKETING_AGENCY_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	28),
		('ICON_BUILDING_JNR_WHARF_BASE_FOW',			'ICON_ATLAS_BUILDINGS_FOW',	22),
		('ICON_BUILDING_JNR_WHARF_FISHING_FOW',			'ICON_ATLAS_BUILDINGS_FOW',	22),
		('ICON_BUILDING_JNR_WHARF_TRADE_FOW',			'ICON_ATLAS_BUILDINGS_FOW',	22),
		('ICON_BUILDING_JNR_LIGHTHOUSE_TRADE_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	10),
		('ICON_BUILDING_JNR_HAVEN_FOW',					'ICON_ATLAS_BUILDINGS_FOW',	22),
		('ICON_BUILDING_JNR_CONSULATE_FOW',				'ICON_ATLAS_BUILDINGS_FOW',	22),
		('ICON_BUILDING_JNR_CRUISE_TERMINAL_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	33);
--------------------------------------------------------------