-- UC_CMP_Text
-- Author: JNR
--------------------------------------------------------------

-- English
--------------------------------------------------------------
INSERT OR IGNORE INTO EnglishText
		(Tag,														Text)
VALUES	('LOC_BUILDING_LIBRARY_DESCRIPTION_UC_JNR',					'+1 additional [ICON_SCIENCE] Science for each era since constructed or last repaired.'),
		('LOC_BUILDING_JNR_ACADEMY_NAME',							'School'),
--		('LOC_BUILDING_JNR_ACADEMY_DESCRIPTION',					'Description'),
--		('LOC_BUILDING_UNIVERSITY_DESCRIPTION_UC_JNR',				'Description'),
		('LOC_BUILDING_JNR_SCHOOL_NAME',							'Academy'),
		('LOC_BUILDING_JNR_SCHOOL_DESCRIPTION',						'+1 [ICON_SCIENCE] Science per [ICON_GOVERNOR] Promotion of a Governor established in this city.'),
--		('LOC_BUILDING_MADRASA_DESCRIPTION_UC_JNR',					'A building unique to Arabia.[NEWLINE]Bonus [ICON_Faith] Faith equal to the adjacency bonus of the Campus district.'),
		('LOC_BUILDING_JNR_LABORATORY_NAME',						'Laboratory'),
		('LOC_BUILDING_JNR_LABORATORY_DESCRIPTION',					'+0.3 [ICON_SCIENCE] Science per turn for each [ICON_Citizen] Citizen in the city.'),
		('LOC_BUILDING_JNR_LIBERAL_ARTS_NAME',						'Liberal Arts College'),
		('LOC_BUILDING_JNR_LIBERAL_ARTS_DESCRIPTION',				'+1 [ICON_SCIENCE] Science from each Great Work in this city.'),
		('LOC_BUILDING_RESEARCH_LAB_NAME_UC_JNR',					'Institute of Technology'),
		('LOC_BUILDING_RESEARCH_LAB_DESCRIPTION_UC_JNR',			'+5% [ICON_Science] Science in this city. Another +5% if the city is powered.'),
		('LOC_BUILDING_JNR_EDUCATION_NAME',							'Community College'),
		('LOC_BUILDING_JNR_EDUCATION_DESCRIPTION',					'Its [ICON_SCIENCE] Science bonus is extended to all City Centers within 6 tiles that do not already have a bonus from this building type.'),
		('LOC_DISTRICT_OBSERVATORY_DESCRIPTION_JNR_UC',				'A district unique to the Maya for scientific endeavors. Replaces the Campus district and cheaper to build.[NEWLINE][NEWLINE]+1 [ICON_Science] Science bonus for adjacent Luxury Resources and Plantations. +1 [ICON_Science] Science bonus for every two adjacent Farm or district tiles.'),
		('LOC_BOOST_TRIGGER_PRINTING_JNR_UC',						'Build 2 Universities or Academies.'),
		('LOC_BOOST_TRIGGER_CHEMISTRY_JNR_UC',						'Build 2 Laboratories.'),
		('LOC_BOOST_TRIGGER_LONGDESC_CHEMISTRY_JNR_UC',				'Running experiments in a controlled environment has improved our understanding of the elements significantly.'),
		('LOC_BOOST_TRIGGER_NUCLEAR_PROGRAM_JNR_UC',				'Build an Institute of Technology.'),
		('LOC_TECH_ASTRONOMY_DESCRIPTION_JNR_UC',					'+50% Campus district adjacency bonuses (+25% in Campuses with a University building) in Campuses adjacent to at least 1 Mountain. Unique Campus replacements do not require an adjacent Mountain.'),
		('LOC_GREATPERSON_ACADEMY_SCIENCE_JNR',						'Schools provide +{Amount} [ICON_SCIENCE] Science.'),
		('LOC_GREATPERSON_SCHOOL_SCIENCE_JNR',						'Academies provide +{Amount} [ICON_SCIENCE] Science.'),
		('LOC_GREATPERSON_LIBERAL_ARTS_SCIENCE_JNR',				'Liberal Arts Colleges provide +{Amount} [ICON_SCIENCE] Science.'),
		('LOC_GREATPERSON_LABORATORY_SCIENCE_JNR',					'Laboratories provide +{Amount} [ICON_SCIENCE] Science.'),
		('LOC_GREATPERSON_INSTITUTE_SCIENCE_JNR',					'Institutes of Technology provide +{Amount} [ICON_SCIENCE] Science.'),
		('LOC_GREATPERSON_EDUCATION_SCIENCE_JNR',					'Community Colleges provide +{Amount} [ICON_SCIENCE] Science.'),
		('LOC_GREATPERSON_ACADEMY_JNR',								'Instantly builds a School in this district.'),
		('LOC_GREATPERSON_SCIENTIFICTHEORYTECHBOOST_JNR',			'Triggers the [ICON_TechBoosted] Eureka moment for Scientific Theory.'),
		('LOC_GREATPERSON_1RENAISSANCEINDUSTRIALCIVICBOOST_JNR',	'Triggers the [ICON_CivicBoosted] Inspiration moment for {Amount} random {Amount : plural 1?civic; other?civics;} from the Renaissance or Industrial era.'),
		('LOC_POLICY_NATURAL_PHILOSOPHY_DESCRIPTION_JNR_UC',		'+100% Campus district adjacency bonuses (+50% in Campuses with a University building).'),
		('LOC_POLICY_FIVE_YEAR_PLAN_DESCRIPTION_JNR_UC_CMP',		'+100% Campus district adjacency bonuses (+50% in Campuses with a University building). +100% Industrial Zone district adjacency bonuses.'),
		('LOC_POLICY_FIVE_YEAR_PLAN_DESCRIPTION_JNR_UC',			'+50% Campus and Industrial Zone district adjacency bonuses (+25% in Campuses with a University building).'),
		('LOC_POLICY_RATIONALISM_DESCRIPTION_JNR_UC',				'Extra [ICON_SCIENCE] Science from buildings in Campuses: +1 if city [ICON_CITIZEN] population is 10 or higher, +1 if district has at least +3 adjacency bonus.'),
		('LOC_POLICY_THIRD_ALTERNATIVE_DESCRIPTION_JNR_UC_CMP',		'+2 [ICON_Culture] Culture and +4 [ICON_Gold] Gold from each Institute of Technology, Community College, Military Academy, Coal Power Plant, Oil Power Plant, and Nuclear Power Plant.'),
		('LOC_POLICY_THIRD_ALTERNATIVE_DESCRIPTION_JNR_UC',			'+100% Encampment district adjacency bonuses. +2 [ICON_Culture] Culture and +4 [ICON_Gold] Gold from each Military Academy, Arsenal, Prison, Institute of Technology, and Community College.'),
		('LOC_DISTRICT_JNR_UC_Floodpains_Grass_Science',			'+{1_num} [ICON_Science] Science from the adjacent Grassland Floodplains tiles.'),
		('LOC_DISTRICT_JNR_UC_Floodpains_Plains_Science',			'+{1_num} [ICON_Science] Science from the adjacent Plains Floodplains tiles.'),
		('LOC_DISTRICT_JNR_UC_Floodpains_Desert_Science',			'+{1_num} [ICON_Science] Science from the adjacent Desert Floodplains tiles.'),
		('LOC_DISTRICT_JNR_UC_Spaceport_Science',					'+{1_num} [ICON_SCIENCE] Science from the adjacent Spaceport {1_Num : plural 2?district; other?districts;}.'),
		('LOC_DISTRICT_JNR_UC_Water_Park_Science',					'+{1_num} [ICON_SCIENCE] Science from the adjacent Water Park {1_Num : plural 2?district; other?districts;}.'),
		('LOC_DISTRICT_JNR_UC_Water_Park_Carnival_Science',			'+{1_num} [ICON_SCIENCE] Science from the adjacent Copacabana {1_Num : plural 2?district; other?districts;}.'),
		('LOC_DISTRICT_JNR_UC_Luxury_Science',						'+{1_num} [ICON_SCIENCE] Science from the adjacent Luxury {1_Num : plural 1?resource; other?resources;}.'),
		('LOC_TRAIT_CIVILIZATION_NOBEL_PRIZE_DESCRIPTION_JNR_UC',	'Sweden gains 50 [ICON_Favor] Diplomatic Favor when earning a Great Person (on Standard Speed). Sweden receives +1 [ICON_GreatEngineer] Great Engineer point from Level 2 Industrial Zone buildings and +1 [ICON_GreatScientist] Great Scientist point from Level 2 Campus buildings. Having Sweden in the game adds three unique World Congress competitions starting in the Industrial Era.'),
		('LOC_EMERGENCY_REWARD_NOBEL_PRIZE_PHY_FIRST_PLACE_UNIVERSITY_RESOURCES_DESCRIPTION_JNR_UC',	'Increases the accumulation of resources in cities with a University or Academy by 1.'),
		('LOC_EMERGENCY_REWARD_NOBEL_PRIZE_PHY_TOP_TIER_UNIVERSITY_RESOURCES_DESCRIPTION_JNR_UC',		'Increases the accumulation of resources in cities with a Laboratory or Liberal Arts College by 1.');
--------------------------------------------------------------

-- Portuguese
--------------------------------------------------------------
INSERT OR IGNORE INTO LocalizedText
		(Language,	Tag,														Text)
VALUES	('pt_BR',	'LOC_BUILDING_LIBRARY_DESCRIPTION_UC_JNR',					'+1 de [ICON_SCIENCE] Cięncia para cada era desde a construçăo ou último reparo.'),
		('pt_BR',	'LOC_BUILDING_JNR_ACADEMY_NAME',							'Escola'),
--		('pt_BR',	'LOC_BUILDING_JNR_ACADEMY_DESCRIPTION',						'Description'),
--		('pt_BR',	'LOC_BUILDING_UNIVERSITY_DESCRIPTION_UC_JNR',				'Description'),
		('pt_BR',	'LOC_BUILDING_JNR_SCHOOL_NAME',								'Academia'),
		('pt_BR',	'LOC_BUILDING_JNR_SCHOOL_DESCRIPTION',						'+1 de [ICON_SCIENCE] Cięncia por promoçăo do [ICON_GOVERNOR] Governador estabelecido nesta cidade.'),
--		('pt_BR',	'LOC_BUILDING_MADRASA_DESCRIPTION_UC_JNR',					'A building unique to Arabia.[NEWLINE]Bonus [ICON_Faith] Faith equal to the adjacency bonus of the Campus district.'),
		('pt_BR',	'LOC_BUILDING_JNR_LABORATORY_NAME',							'Laboratório'),
		('pt_BR',	'LOC_BUILDING_JNR_LABORATORY_DESCRIPTION',					'+0.3 de [ICON_SCIENCE] Cięncia por turno por [ICON_Citizen] Cidadăo na cidade.'),
		('pt_BR',	'LOC_BUILDING_JNR_LIBERAL_ARTS_NAME',						'Faculdade de Artes Liberais'),
		('pt_BR',	'LOC_BUILDING_JNR_LIBERAL_ARTS_DESCRIPTION',				'+1 de [ICON_SCIENCE] Cięncia de cada Grande Obra na cidade.'),
		('pt_BR',	'LOC_BUILDING_RESEARCH_LAB_NAME_UC_JNR',					'Instituto de Tecnologia'),
		('pt_BR',	'LOC_BUILDING_RESEARCH_LAB_DESCRIPTION_UC_JNR',				'+5% de [ICON_SCIENCE] Cięncia nesta cidade. +5% Adicional se a cidade estiver energizada.'),
		('pt_BR',	'LOC_BUILDING_JNR_EDUCATION_NAME',							'Universidade Comunitária'),
		('pt_BR',	'LOC_BUILDING_JNR_EDUCATION_DESCRIPTION',					'Seu bônus de [ICON_SCIENCE] Cięncia é extendido para todos os Centros de Cidade em até 6 painéis que já năo recebam bônus desse tipo de edificaçăo.'),
		('pt_BR',	'LOC_DISTRICT_OBSERVATORY_DESCRIPTION_JNR_UC',				'Um distrito único da civilizaçăo Maia para assuntos científicos. Subsititui o Campus e é mais barato para se construir.[NEWLINE][NEWLINE]+1 de [ICON_SCIENCE] Cięncia por recursos de luxo ou melhorias de plantaçőes nos painéis adjacentes. +1 de [ICON_SCIENCE] Cięncia para cada 2 painéis com melhorias de fazenda. +1 de [ICON_SCIENCE] Cięncia para cada 2 painéis de distritos.'),
		('pt_BR',	'LOC_BOOST_TRIGGER_PRINTING_JNR_UC',						'Construa 2 Universidades ou Academias.'),
		('pt_BR',	'LOC_BOOST_TRIGGER_CHEMISTRY_JNR_UC',						'Construa 2 Laboratórios.'),
		('pt_BR',	'LOC_BOOST_TRIGGER_LONGDESC_CHEMISTRY_JNR_UC',				'Long Description'),
		('pt_BR',	'LOC_BOOST_TRIGGER_NUCLEAR_PROGRAM_JNR_UC',					'Construa um Instituto de Tecnologia.'),
		('pt_BR',	'LOC_TECH_ASTRONOMY_DESCRIPTION_JNR_UC',					'+50% de bônus de adjacęncia para Campi (+25% se tiver uma edificaçăo de Universidade) adjacentes a pelo menos 1 painel de Montanha. Distritos únicos que substituem o Campus năo requerem uma Montanha adjacente.'),
		('pt_BR',	'LOC_GREATPERSON_ACADEMY_SCIENCE_JNR',						'Escolas dăo +{Amount} de [ICON_SCIENCE] Cięncia.'),
		('pt_BR',	'LOC_GREATPERSON_SCHOOL_SCIENCE_JNR',						'Academias dăo +{Amount} de [ICON_SCIENCE] Cięncia.'),
		('pt_BR',	'LOC_GREATPERSON_LIBERAL_ARTS_SCIENCE_JNR',					'Faculdades de Artes Liberais dăo +{Amount} de [ICON_SCIENCE] Cięncia.'),
		('pt_BR',	'LOC_GREATPERSON_LABORATORY_SCIENCE_JNR',					'Laboratórios dăo +{Amount} de [ICON_SCIENCE] Cięncia.'),
		('pt_BR',	'LOC_GREATPERSON_INSTITUTE_SCIENCE_JNR',					'Institutos de Tecnologia dăo +{Amount} de [ICON_SCIENCE] Cięncia.'),
		('pt_BR',	'LOC_GREATPERSON_EDUCATION_SCIENCE_JNR',					'Universidades Comunitária dăo +{Amount} de [ICON_SCIENCE] Cięncia.'),
		('pt_BR',	'LOC_GREATPERSON_ACADEMY_JNR',								'Constói uma Escola imediatamente neste distrito.'),
		('pt_BR',	'LOC_GREATPERSON_SCIENTIFICTHEORYTECHBOOST_JNR',			'Dá o momento de [ICON_TechBoosted] Eureka para Teoria Científica.'),
		('pt_BR',	'LOC_GREATPERSON_1RENAISSANCEINDUSTRIALCIVICBOOST_JNR',		'Dá o momento de [ICON_CivicBoosted] Inspiraçăo para {Amount} {Amount : plural 1?cívico; other?cívicos;} da Era Renascentista ou Industrial.'),
		('pt_BR',	'LOC_POLICY_NATURAL_PHILOSOPHY_DESCRIPTION_JNR_UC',			'+100% de bônus de adjacęncia para Campi sem uma edificaçăo de Universidade. +50% em Campi com uma edificaçăo de Universidade.'),
		('pt_BR',	'LOC_POLICY_FIVE_YEAR_PLAN_DESCRIPTION_JNR_UC_CMP',			'+100% de bônus de adjacęncia para Campi sem uma edificaçăo de Universidade. +50% em Campi com uma edificaçăo de Universidade. +100% Industrial Zone district adjacency bonuses.'),
		('pt_BR',	'LOC_POLICY_FIVE_YEAR_PLAN_DESCRIPTION_JNR_UC',				'+50% de bônus de adjacęncia para Campus e Zonas Industriais (+25% em Campi com uma edificaçăo de Universidade).'),
		('pt_BR',	'LOC_POLICY_RATIONALISM_DESCRIPTION_JNR_UC',				'[ICON_SCIENCE] Cięncia extra de edificaçőes em Campi: +1 se a [ICON_CITIZEN] Populaçăo da cidade é 10 ou maior, +1 se o distrito tiver um bônus de adjacęncia de pelo menos +3.'),
		('pt_BR',	'LOC_POLICY_THIRD_ALTERNATIVE_DESCRIPTION_JNR_UC_CMP',		'+2 de [ICON_Culture] Cultura e +4 de [ICON_Gold] Ouro de cada Instituto de Tecnologia, Universidade Comunitária, Academia Militar, Usina de Força a Carvăo, Usina de Força a Óleo and Usina de Força Nuclear.'),
		('pt_BR',	'LOC_POLICY_THIRD_ALTERNATIVE_DESCRIPTION_JNR_UC',			'+100% de bônus de adjacęncia para Acampamentos. +2 [ICON_Culture] Culture and +4 [ICON_Gold] Gold from each Academia Militar, Paiol, Prisăo, Instituto de Tecnologia e Universidade Comunitária.'),
		('pt_BR',	'LOC_DISTRICT_JNR_UC_Floodpains_Grass_Science',				'+{1_num} de [ICON_SCIENCE] Cięncia dos painéis de Pradaria Aluvial.'),
		('pt_BR',	'LOC_DISTRICT_JNR_UC_Floodpains_Plains_Science',			'+{1_num} de [ICON_SCIENCE] Cięncia dos painéis de Planície Aluvial.'),
		('pt_BR',	'LOC_DISTRICT_JNR_UC_Floodpains_Desert_Science',			'+{1_num} de [ICON_SCIENCE] Cięncia dos painéis de Deserto Aluvial.'),
		('pt_BR',	'LOC_DISTRICT_JNR_UC_Spaceport_Science',					'+{1_num} de [ICON_SCIENCE] Cięncia {1_Num : plural 2?do Espaçoporto adjacente; other?dos Espaçoportos adjacentes;}.'),
		('pt_BR',	'LOC_DISTRICT_JNR_UC_Water_Park_Science',					'+{1_num} de [ICON_SCIENCE] Cięncia {1_Num : plural 2?do Parque Aquático adjacente; other?dos Parques Aquáticos adjacentes;}.'),
		('pt_BR',	'LOC_DISTRICT_JNR_UC_Water_Park_Carnival_Science',			'+{1_num} de [ICON_SCIENCE] Cięncia {1_Num : plural 2?do Copacabana adjacente; other?dos Copacabanas adjacentes;}.'),
		('pt_BR',	'LOC_DISTRICT_JNR_UC_Luxury_Science',						'+{1_num} de [ICON_SCIENCE] Cięncia {1_Num : plural 1?do Recurso de Luxo adjacente; other?dos Recursos de Luxo adjacentes;}.'),
		('pt_BR',	'LOC_TRAIT_CIVILIZATION_NOBEL_PRIZE_DESCRIPTION_JNR_UC',	'Suécia ganha 50 de [ICON_Favor] Favor Diplomático quando recruta uma Grande Personalidade (na velocidade padrăo). Suécia recebe +1 ponto de [ICON_GreatEngineer] Great Engenheiro de edifícios nível 2 de Zona Industrial e +1 ponto de [ICON_GreatScientist] Grande Cientista de edificaçőes nível 2 de Campus. Quando Suécia está no jogo adiciona 3 competiçőes únicas no Congresso Mundial iniciando na Era Industrial.'),
		('pt_BR',	'LOC_EMERGENCY_REWARD_NOBEL_PRIZE_PHY_FIRST_PLACE_UNIVERSITY_RESOURCES_DESCRIPTION_JNR_UC',	'Aumenta o acúmulo de recursos em cidades com uma Universidade ou Academia em 1.'),
		('pt_BR',	'LOC_EMERGENCY_REWARD_NOBEL_PRIZE_PHY_TOP_TIER_UNIVERSITY_RESOURCES_DESCRIPTION_JNR_UC',		'Aumenta o acúmulo de recursos em cidades com um Laboratório ou Faculdades de Artes Liberais em 1.');
--------------------------------------------------------------